version: '3'

services:
  nginx:  # 컨테이너의 이름
    image: nginx:latest
    ports: 
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  web1:
    build: . # 현재경로에 있는 Dockerfile 참조해서 Build 시작
    command: gunicorn fisa_django.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile -
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

